<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Quality Certificate {{ $grade->certificate_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1a1a; }
        .header { text-align: center; border-bottom: 3px solid #2E7D32; padding-bottom: 16px; margin-bottom: 24px; }
        .header h1 { font-size: 22px; color: #2E7D32; margin: 0; }
        .header p { margin: 4px 0; color: #555; }
        .cert-number { font-size: 18px; font-weight: bold; color: #E65100; }
        .section { margin-bottom: 20px; }
        .section h3 { border-bottom: 1px solid #aaa; padding-bottom: 4px; color: #2E7D32; }
        table { width: 100%; border-collapse: collapse; }
        table td { padding: 6px 8px; border: 1px solid #ddd; }
        table td:first-child { font-weight: bold; width: 40%; background: #f5f5f5; }
        .grade-badge { display: inline-block; padding: 4px 12px; font-size: 16px; font-weight: bold; border-radius: 4px; }
        .grade-A { background: #C8E6C9; color: #1B5E20; }
        .grade-B { background: #FFF9C4; color: #F57F17; }
        .grade-C { background: #FFE0B2; color: #E65100; }
        .grade-rejected { background: #FFCDD2; color: #B71C1C; }
        .footer { margin-top: 40px; border-top: 1px solid #aaa; padding-top: 12px; font-size: 10px; color: #777; }
        .qr-placeholder { text-align: center; margin: 20px 0; }
        .hash { font-family: monospace; font-size: 9px; word-break: break-all; color: #555; }
        .signature-block { margin-top: 40px; display: flex; justify-content: space-between; }
        .sig-line { border-top: 1px solid #333; width: 200px; text-align: center; padding-top: 4px; font-size: 10px; }
    </style>
</head>
<body>

<div class="header">
    <h1>TERA HARVEST — QUALITY CERTIFICATE</h1>
    <p>Ethiopian Agricultural Supply Chain Platform</p>
    <div class="cert-number">{{ $grade->certificate_number }}</div>
</div>

<div class="section">
    <h3>Certificate Details</h3>
    <table>
        <tr><td>Certificate Number</td><td>{{ $grade->certificate_number }}</td></tr>
        <tr><td>Grading Standard</td><td>{{ strtoupper($grade->grading_standard) }}</td></tr>
        <tr><td>Date Issued</td><td>{{ $grade->graded_at?->format('d M Y H:i') }}</td></tr>
        <tr><td>Status</td><td>{{ strtoupper($grade->status) }}</td></tr>
    </table>
</div>

<div class="section">
    <h3>Produce Details</h3>
    <table>
        <tr><td>Crop Type</td><td>{{ ucfirst($grade->crop_type) }}</td></tr>
        <tr><td>Weight (kg)</td><td>{{ number_format($grade->weight_kg, 3) }}</td></tr>
        <tr>
            <td>Overall Grade</td>
            <td>
                <span class="grade-badge grade-{{ $grade->overall_grade }}">
                    {{ strtoupper($grade->overall_grade) }}
                </span>
            </td>
        </tr>
        @if($grade->shipment_id)
        <tr><td>Shipment ID</td><td>{{ $grade->shipment_id }}</td></tr>
        @endif
    </table>
</div>

<div class="section">
    <h3>Quality Metrics</h3>
    <table>
        <tr><td>Moisture (%)</td><td>{{ $grade->moisture_pct ?? 'N/A' }}</td></tr>
        <tr><td>Foreign Matter (%)</td><td>{{ $grade->foreign_matter_pct ?? 'N/A' }}</td></tr>
        <tr><td>Defect Rate (%)</td><td>{{ $grade->defect_pct ?? 'N/A' }}</td></tr>
        <tr><td>Colour Score (1-5)</td><td>{{ $grade->colour_score ?? 'N/A' }}</td></tr>
        <tr><td>Smell Score (1-5)</td><td>{{ $grade->smell_score ?? 'N/A' }}</td></tr>
    </table>
</div>

@if($grade->notes)
<div class="section">
    <h3>Inspector Notes</h3>
    <p>{{ $grade->notes }}</p>
</div>
@endif

<div class="section">
    <h3>Tamper Detection</h3>
    <p>SHA-256 Document Hash:</p>
    <p class="hash">{{ $grade->certificate_hash ?? 'Computed on generation' }}</p>
    <p>Verify at: <strong>/api/v1/quality/grades/{{ $grade->id }}/verify</strong></p>
</div>

<div class="signature-block">
    <div class="sig-line">Inspector Signature</div>
    <div class="sig-line">Issuing Authority</div>
    <div class="sig-line">Date</div>
</div>

<div class="footer">
    <p>This certificate was digitally generated by Tera Harvest. The SHA-256 hash above guarantees tamper-evidence.
       Scan the QR code or visit the verify URL to confirm authenticity.</p>
    <p>Generated: {{ now()->format('d M Y H:i:s') }} EAT</p>
</div>

</body>
</html>
